name: example
description: Envied example
version: 2.2.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  envied: ^1.3.1

dev_dependencies:
  build_runner: ^2.10.4
  envied_generator: ^1.3.1
  lints: ^6.0.0
  test: ^1.28.0
