name: envied_generator
description: Generator for the Envied package. See https://pub.dev/packages/envied.
version: 0.4.0
repository: https://github.com/petercinibulk/envied
homepage: https://github.com/petercinibulk/envied

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  envied: ^0.4.0
  build: ^2.4.1
  code_builder: ^4.6.0
  dart_style: ^2.3.2
  source_gen: ^1.4.0
  analyzer: ">=5.1.0 <7.0.0"

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
  source_gen_test: ^1.0.6

topics:
  - environment-variables
  - dotenv
  - codegen