name: envied_generator
description: Generator for the Envied package. See https://pub.dev/packages/envied.
version: 0.3.0+1
repository: https://github.com/petercinibulk/envied
homepage: https://github.com/petercinibulk/envied

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  envied: ^0.3.0+1
  build: ^2.4.0
  source_gen: ^1.3.1
  analyzer: ^5.12.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
  source_gen_test: ^1.0.5
