name: envied_generator
description: Generator for the Envied package. See https://pub.dev/packages/envied.
version: 1.1.1
repository: https://github.com/petercinibulk/envied
homepage: https://github.com/petercinibulk/envied

environment:
  sdk: ^3.0.0

dependencies:
  envied: ^1.1.0
  build: ">=2.4.1 <4.0.0"
  code_builder: ^4.8.0
  source_gen: ">=1.4.0 <4.0.0"
  analyzer: ">=5.1.0 <8.0.0"
  recase: ^4.1.0
  equatable: ^2.0.5

dev_dependencies:
  lints: ">=4.0.0 <7.0.0"
  test: ^1.24.6
  source_gen_test: ^1.0.6

topics:
  - environment-variables
  - dotenv
  - codegen
