name: envied_generator
description: Generator for the Envied package. See https://pub.dev/packages/envied.
version: 1.3.2
repository: https://github.com/petercinibulk/envied
homepage: https://github.com/petercinibulk/envied

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ">=8.0.0 <10.0.0"
  build: ^4.0.3
  code_builder: ^4.11.0
  envied: ^1.3.1
  equatable: ^2.0.7
  recase: ^4.1.0
  source_gen: ^4.1.1

dev_dependencies:
  lints: ^6.0.0
  source_gen_test: ^1.3.3
  test: ^1.28.0

topics:
  - environment-variables
  - dotenv
  - codegen
