name: envied_generator
description: Generator for the Envied package. See https://pub.dev/packages/envied.
version: 0.2.3+1
repository: https://github.com/petercinibulk/envied
homepage: https://github.com/petercinibulk/envied
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  envied:
    git:
      url: https://github.com/kaankoken/envied.git
      ref: feature/test-default-value
      path: packages/envied
  build: ^2.3.0
  source_gen: ^1.2.2
  analyzer: ^5.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  source_gen_test: ^1.0.3
