name: envied_generator
description: Handles environment variables in dart from a .env file.
version: 0.1.0
repository: https://github.com/petercinibulk/envied
homepage: https://github.com/petercinibulk/envied

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  envied: ^0.1.0
  build: ^2.3.0
  dotenv: ^4.0.1
  source_gen: ^1.2.2
  analyzer: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  source_gen_test: ^1.0.3
