name: envied
description: Explicitly reads environment variables into a dart file from a .env file for more security and faster start up times.
version: 1.3.3
repository: https://github.com/petercinibulk/envied
homepage: https://github.com/petercinibulk/envied

environment:
  sdk: ^3.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0

topics:
  - environment-variables
  - dotenv
