name: envied
description: Explicitly reads environment variables into a dart file from a .env file for more security and faster start up times.
version: 0.3.0
repository: https://github.com/petercinibulk/envied
homepage: https://github.com/petercinibulk/envied

environment:
  sdk: ">=2.17.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
